OPEN SYMMETRIC KEY IMDB_ColumnKey
    DECRYPTION BY CERTIFICATE IMDB_tdeCert;
UPDATE ITEMS
SET PIINumber = ENCRYPTBYKEY(KEY_GUID('IMDB_ColumnKey'), PIINumberBackup)
CLOSE SYMMETRIC KEY IMDB_ColumnKey;